name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: inzumer/inzumer-ci/.github/workflows/node-ci.yml@v1
    with:
      audit-level: low
      commands: |
        pnpm check
        npm pack --dry-run
